___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [2]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [5]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [10]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [13]:
ary= np.arange(16).reshape(4,4)
ary[:,:]=7      #[:]=7
ary

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [11]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [14]:
array= np.arange (2,17,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16])

 8. Create a 5x5 matrix with values between 0 to 25

In [14]:
arry= np.arange(0,25).reshape(5,5)
arry

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [15]:
lins=np.linspace (0,24,25, dtype=int).reshape(5,5)
lins

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [28]:
np.random.randn(5)

array([ 0.6607066 , -0.04120939,  0.56902563,  0.34090352,  1.81247223])

#### 11. Create random normal distributed 5x5 array

In [29]:
np.random.randn(5,5)

array([[ 0.69076653,  1.31509505, -1.30086767,  0.23958198, -1.51222571],
       [-0.04157935,  0.05193478, -2.1673329 , -0.08353591, -0.19202732],
       [ 0.87037008, -0.83292368, -0.80879724,  1.64553378,  1.03887614],
       [ 0.86212487, -0.3149073 , -0.69856725,  0.47909022, -1.20515478],
       [ 0.02483328,  1.74421299, -0.17313461,  0.15616787, -0.52454348]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [16]:
arry= np.random.randint(20,50,12).reshape(3,4)
arry

array([[38, 30, 41, 27],
       [37, 23, 22, 32],
       [32, 22, 23, 45]])

#### 13. Reshape the array below with shape 6x8

In [17]:
ranarr = np.random.randint(0, 60, 48)

In [22]:
ranarr.reshape(6,8)

array([[ 8, 57,  7,  0, 33,  5, 29, 14],
       [25, 18, 24, 32, 48, 23, 44, 42],
       [41, 59, 34, 34,  3, 47, 30,  0],
       [46, 39, 59,  5, 32, 53, 28, 44],
       [49, 17, 19, 14,  0, 37, 51, 12],
       [22, 45, 30, 15, 36, 42,  0, 42]])

In [27]:
ranarr. reshape (6,-1) #reshape with -1

array([[ 8, 57,  7,  0, 33,  5, 29, 14],
       [25, 18, 24, 32, 48, 23, 44, 42],
       [41, 59, 34, 34,  3, 47, 30,  0],
       [46, 39, 59,  5, 32, 53, 28, 44],
       [49, 17, 19, 14,  0, 37, 51, 12],
       [22, 45, 30, 15, 36, 42,  0, 42]])

## Numpy Indexing and Selection


In [3]:
#Create array below
ary1= np.arange(1,17).reshape(4,4)
ary1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [76]:
ary1[1:3,1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### 15. Get the first column of the array.

In [41]:
ary1[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [75]:
ary1[1,0::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [6]:
ary1[:,2:3]=77
ary1

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [105]:
ary1[[1,3],[0,2]]

array([[ 5,  6, 77,  8],
       [13, 14, 77, 16]])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [10]:
ary1[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [22]:
s=ary1[ary1<10]
s

array([1, 2, 4, 5, 6, 8, 9])

In [23]:
b=ary1[ary1>12]
s

array([1, 2, 4, 5, 6, 8, 9])

In [25]:
ary2=s+b
ary2

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [27]:
ary2.std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [105]:
#print array here

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [28]:
np.sum(ary1[:,1])

32

#### 23. Get the median,mean and std of 3rd column from array above

In [30]:
ary1last= np.arange(1,17).reshape(4,4)
ary1last

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
#median
np.median(ary1last[:,2])

9.0

In [32]:
#mean
np.mean(ary1last[:,2])

9.0

In [33]:
ary1last[:,2].mean()

9.0

In [36]:
#std
np.std(ary1last[:,2])

4.47213595499958

# Pandas Section

In [1]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [2]:
df= pd.read_csv("Salaries.csv")


In [3]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


**How many different year value are there**

In [131]:
df.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [132]:
#max
df.TotalPay.max()

567595.43

In [6]:
#avg
avg=df.TotalPay.mean()
avg

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [7]:
(df.TotalPay>avg).sum()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [8]:
df.TotalPayBenefits[df.EmployeeName== "ALBERT PARDINI"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [9]:
df.min()["TotalPayBenefits"]

-618.13

In [10]:
df["EmployeeName"][df.TotalPay.argmin()]

'Joe Lopez'

**What are the unique Jobs in dataset?**

In [12]:
df["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [13]:
df['JobTitle'].value_counts().tail(3)

ADMINISTRATOR, SFGH MEDICAL CENTER       1
AUDIOLOGIST                              1
COURT COMPUTER FACILITIES COORDINATOR    1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [14]:
df.Id[(df["Year"]==2012)&(df["TotalPayBenefits"]>df["TotalPayBenefits"].mean())]

36159    36160
36160    36161
36161    36162
36162    36163
36163    36164
         ...  
56520    56521
56521    56522
56522    56523
56523    56524
56524    56525
Name: Id, Length: 20366, dtype: int64

In [15]:
df.Id[(df["Year"]==2012)&(df["TotalPayBenefits"]>df["TotalPayBenefits"].mean())].count()

20366

**How many people have the word Manager in their job title?**

In [16]:
#use apply function here
def jobtitle(name):
    if "manager" in name.lower():
        return True
    else:
        return False
sum(df["JobTitle"].apply(lambda x: jobtitle(x)))

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [17]:
sal_new = df. iloc[:, [0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [18]:
sal_new1 = df.loc [: , ["EmployeeName", "JobTitle", "TotalPay", "TotalPayBenefits"]]
sal_new1

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [19]:
df["EmployeeName"][(df["TotalPayBenefits"]> df["TotalPayBenefits"].min()) & (df["TotalPay"]< df["TotalPay"].mean())]

15847     TATYANA ROTENBERG
15848           WINSTON HOM
15849          CRAIG RIGLER
15850             WENDY TAN
15851        KENNETH BREWER
                ...        
148648          Leon Walker
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
Name: EmployeeName, Length: 79164, dtype: object